DROP TABLE IF EXISTS trainersEntities;
DROP TABLE IF EXISTS orderitems;
DROP TABLE IF EXISTS evolutionChains;
DROP TABLE IF EXISTS pokemonToTypes CASCADE;
DROP TABLE IF EXISTS pokemon;
DROP TABLE IF EXISTS stoneWiki;
DROP TABLE IF EXISTS pokemonWiki;
DROP TABLE IF EXISTS baseStats;
DROP TABLE IF EXISTS pokemonTypes;
DROP TABLE IF EXISTS inStock CASCADE ;
DROP TABLE IF EXISTS orderStatuses CASCADE ;
DROP TABLE IF EXISTS orders CASCADE ;
DROP TABLE IF EXISTS entities CASCADE ;
DROP TABLE IF EXISTS wikiTypes CASCADE ;
DROP TABLE IF EXISTS trainers CASCADE ;
DROP TABLE IF EXISTS gameStylesDist CASCADE ;
DROP TABLE IF EXISTS _user CASCADE ;



